/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanylsanbong.view;

import Clock.MyClock;
import Utils.CheckText;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlysanbong.controller.AccountDAO;
import quanlysanbong.controller.DichVuDAO;
import quanlysanbong.controller.KhachHangDAO;
import quanlysanbong.controller.StaffDAO;
import quanlysanbong.model.DichVu;
import quanlysanbong.model.KhachHang;
import quanlysanbong.model.NhanVien;

/**
 *
 * @author tranh
 */
public class StaffGUI extends javax.swing.JFrame {

    private StaffDAO staffDao = new StaffDAO();
    private KhachHangDAO khDao = new KhachHangDAO();
    private AccountDAO accDao = new AccountDAO();
    private DichVuDAO dvDao = new DichVuDAO();

    private NhanVien staff;
    
    private ArrayList<KhachHang> khList;
    private DefaultTableModel khTableModel;
    
    private DefaultTableModel dvTableModel;
    private ArrayList<DichVu> dvList;

    /**
     * Creates new form StaffGUI
     */
    public StaffGUI(String username, String role) {
        initComponents();
        this.getContentPane().setBackground(new Color(242, 222, 135));
        this.setLocationRelativeTo(null);

        usernameLabel.setText(username);
        roleLabel.setText(role);

        staff = staffDao.getStaff(username);
        showInfo();
        
        khTableModel = (DefaultTableModel) khTable.getModel();
        khList = khDao.getCustomerList();
        showCusList(khList);
        
        dvTableModel = (DefaultTableModel) foodTable.getModel();
        dvList = dvDao.getDichVuList();
        showFoodList(dvList);
        
        //set clock
        MyClock clock = new MyClock(timeLabel, dateLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        infoBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        bookingBtn = new javax.swing.JButton();
        viewFoodBtn = new javax.swing.JButton();
        viewMapBtn = new javax.swing.JButton();
        roleLabel = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        payBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        viewMapPanel = new javax.swing.JPanel();
        bookingPanel = new javax.swing.JPanel();
        customerPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        khTable = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        cusIdTxt = new javax.swing.JTextField();
        cusIdWrong = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cusFnameTxt = new javax.swing.JTextField();
        cusFnameWrong = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cusLnameTxt = new javax.swing.JTextField();
        cusLnameWrong = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cusPhoneTxt = new javax.swing.JTextField();
        cusPhoneWrong = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cusCmndTxt = new javax.swing.JTextField();
        cusCmndWrong = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        cusUsernameTxt = new javax.swing.JTextField();
        cusUsernameWrong = new javax.swing.JLabel();
        addCusBtn = new javax.swing.JButton();
        updateCusBtn = new javax.swing.JButton();
        cancelCusBtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        sortCusCbBox = new javax.swing.JComboBox<>();
        viewFoodPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodTable = new javax.swing.JTable();
        foodImageLabel = new javax.swing.JLabel();
        dischargePanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        fnameTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lnameTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmndTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quitYesRadio = new javax.swing.JRadioButton();
        quitNoRadio = new javax.swing.JRadioButton();
        fnameWrong = new javax.swing.JLabel();
        lnameWrong = new javax.swing.JLabel();
        phoneWrong = new javax.swing.JLabel();
        cmndWrong = new javax.swing.JLabel();
        settingBtn = new javax.swing.JButton();
        changepwdBtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-user-50.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Unispace", 2, 14)); // NOI18N
        jLabel2.setText("Hello");

        usernameLabel.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        usernameLabel.setText("username");

        infoBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-info-32.png"))); // NOI18N
        infoBtn.setText("User Info");
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-logout-32.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        bookingBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        bookingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-booking-32.png"))); // NOI18N
        bookingBtn.setText("Booking Stadium");
        bookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingBtnActionPerformed(evt);
            }
        });

        viewFoodBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        viewFoodBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-soda-32.png"))); // NOI18N
        viewFoodBtn.setText("View Drinks and Foods");
        viewFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFoodBtnActionPerformed(evt);
            }
        });

        viewMapBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        viewMapBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-stadium-32.png"))); // NOI18N
        viewMapBtn.setText("View Map");
        viewMapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMapBtnActionPerformed(evt);
            }
        });

        roleLabel.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        roleLabel.setText("role");

        jLabel22.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel22.setText("Role:");

        payBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        payBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-money-32.png"))); // NOI18N
        payBtn.setText("Discharge");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        customerBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        customerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-human-32.png"))); // NOI18N
        customerBtn.setText("Customer");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-clock-50.png"))); // NOI18N
        jLabel26.setText(" ");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        timeLabel.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("hh:mm:ss");

        dateLabel.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("E, dd/MM/yyyy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoBtn)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewFoodBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(viewMapBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(infoBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutBtn)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(usernameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(roleLabel)
                                    .addComponent(jLabel22))))))
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookingBtn)
                .addGap(18, 18, 18)
                .addComponent(viewMapBtn)
                .addGap(18, 18, 18)
                .addComponent(customerBtn)
                .addGap(18, 18, 18)
                .addComponent(viewFoodBtn)
                .addGap(18, 18, 18)
                .addComponent(payBtn)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(timeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        viewMapPanel.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout viewMapPanelLayout = new javax.swing.GroupLayout(viewMapPanel);
        viewMapPanel.setLayout(viewMapPanelLayout);
        viewMapPanelLayout.setHorizontalGroup(
            viewMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        viewMapPanelLayout.setVerticalGroup(
            viewMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );

        bookingPanel.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout bookingPanelLayout = new javax.swing.GroupLayout(bookingPanel);
        bookingPanel.setLayout(bookingPanelLayout);
        bookingPanelLayout.setHorizontalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        bookingPanelLayout.setVerticalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );

        customerPanel.setBackground(new java.awt.Color(255, 255, 204));

        khTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First name", "Last name", "Phone", "Personal ID", "Number of rent", "Username", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        khTable.getTableHeader().setReorderingAllowed(false);
        khTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(khTable);

        jLabel18.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel18.setText("ID");

        cusIdWrong.setForeground(new java.awt.Color(255, 0, 51));
        cusIdWrong.setText(" ");

        jLabel20.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel20.setText("Fname");

        cusFnameWrong.setForeground(new java.awt.Color(255, 0, 51));
        cusFnameWrong.setText(" ");

        jLabel25.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel25.setText("Lname");

        cusLnameWrong.setForeground(new java.awt.Color(255, 0, 51));
        cusLnameWrong.setText(" ");

        jLabel27.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel27.setText("Phone");

        cusPhoneWrong.setForeground(new java.awt.Color(255, 0, 51));
        cusPhoneWrong.setText(" ");

        jLabel29.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel29.setText("P-ID");

        cusCmndWrong.setForeground(new java.awt.Color(255, 0, 51));
        cusCmndWrong.setText(" ");

        jLabel31.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel31.setText("Username");

        cusUsernameWrong.setForeground(new java.awt.Color(255, 0, 51));
        cusUsernameWrong.setText(" ");

        addCusBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        addCusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-add-32.png"))); // NOI18N
        addCusBtn.setText("Add");
        addCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCusBtnActionPerformed(evt);
            }
        });

        updateCusBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        updateCusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-update-32.png"))); // NOI18N
        updateCusBtn.setText("Update");
        updateCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCusBtnActionPerformed(evt);
            }
        });

        cancelCusBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        cancelCusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-cancel-32.png"))); // NOI18N
        cancelCusBtn.setText("Cancel");
        cancelCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCusBtnActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel19.setText("Sort by:");

        sortCusCbBox.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        sortCusCbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Last name", "Number of rent" }));
        sortCusCbBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sortCusCbBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cusIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusIdWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, customerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cusFnameWrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cusFnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, customerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cusPhoneWrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cusPhoneTxt)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, customerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(3, 3, 3)
                                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cusUsernameWrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cusUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(83, 83, 83)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(customerPanelLayout.createSequentialGroup()
                                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cusLnameWrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cusLnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cusCmndTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cusCmndWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sortCusCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(customerPanelLayout.createSequentialGroup()
                                .addComponent(addCusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateCusBtn)))
                        .addGap(56, 56, 56)
                        .addComponent(cancelCusBtn)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cusIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(sortCusCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusIdWrong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cusFnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(cusLnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusFnameWrong)
                    .addComponent(cusLnameWrong))
                .addGap(18, 18, 18)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cusPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(cusCmndTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusPhoneWrong)
                    .addComponent(cusCmndWrong))
                .addGap(18, 18, 18)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(cusUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addCusBtn)
                        .addComponent(updateCusBtn)
                        .addComponent(cancelCusBtn))
                    .addComponent(cusUsernameWrong))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        viewFoodPanel.setBackground(new java.awt.Color(255, 255, 204));

        foodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Unit", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        foodTable.getTableHeader().setReorderingAllowed(false);
        foodTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(foodTable);

        foodImageLabel.setBackground(new java.awt.Color(255, 255, 255));
        foodImageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout viewFoodPanelLayout = new javax.swing.GroupLayout(viewFoodPanel);
        viewFoodPanel.setLayout(viewFoodPanelLayout);
        viewFoodPanelLayout.setHorizontalGroup(
            viewFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewFoodPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(foodImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        viewFoodPanelLayout.setVerticalGroup(
            viewFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewFoodPanelLayout.createSequentialGroup()
                .addGroup(viewFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewFoodPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewFoodPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(foodImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        dischargePanel.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout dischargePanelLayout = new javax.swing.GroupLayout(dischargePanel);
        dischargePanel.setLayout(dischargePanelLayout);
        dischargePanelLayout.setHorizontalGroup(
            dischargePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        dischargePanelLayout.setVerticalGroup(
            dischargePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );

        infoPanel.setBackground(new java.awt.Color(255, 255, 204));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel4.setText("ID Work");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel5.setText("FName");

        idTxt.setBackground(new java.awt.Color(242, 242, 242));
        idTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        idTxt.setEnabled(false);

        fnameTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fnameTxt.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel6.setText("LName");

        lnameTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lnameTxt.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel7.setText("Phone");

        phoneTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        phoneTxt.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel8.setText("ID");

        cmndTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmndTxt.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel3.setText("Off");

        quitYesRadio.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        quitYesRadio.setText("Yes");
        quitYesRadio.setEnabled(false);
        quitYesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitYesRadioActionPerformed(evt);
            }
        });

        quitNoRadio.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        quitNoRadio.setText("No");
        quitNoRadio.setEnabled(false);
        quitNoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitNoRadioActionPerformed(evt);
            }
        });

        fnameWrong.setForeground(new java.awt.Color(255, 0, 51));
        fnameWrong.setText(" ");

        lnameWrong.setForeground(new java.awt.Color(255, 0, 51));
        lnameWrong.setText(" ");

        phoneWrong.setForeground(new java.awt.Color(255, 0, 51));
        phoneWrong.setText(" ");

        cmndWrong.setForeground(new java.awt.Color(255, 0, 0));
        cmndWrong.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(quitNoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quitYesRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmndTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                        .addComponent(phoneTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(fnameWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lnameWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(phoneWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmndWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fnameWrong)
                    .addComponent(lnameWrong))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(5, 5, 5)
                .addComponent(phoneWrong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmndTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(cmndWrong)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quitYesRadio)
                    .addComponent(quitNoRadio))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        settingBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        settingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-setting-32.png"))); // NOI18N
        settingBtn.setText("Settings");
        settingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingBtnActionPerformed(evt);
            }
        });

        changepwdBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        changepwdBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/change-pwd-icon.png"))); // NOI18N
        changepwdBtn.setText("Change password");

        savebtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-save-32.png"))); // NOI18N
        savebtn.setText("Save");
        savebtn.setEnabled(false);
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlysanbong/images/icons8-cancel-32.png"))); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.setEnabled(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(settingBtn)
                        .addGap(71, 71, 71)
                        .addComponent(changepwdBtn)
                        .addGap(59, 59, 59)
                        .addComponent(savebtn)
                        .addGap(88, 88, 88)
                        .addComponent(cancelBtn)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingBtn)
                    .addComponent(changepwdBtn)
                    .addComponent(savebtn)
                    .addComponent(cancelBtn))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewMapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(customerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewFoodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dischargePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewMapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(customerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewFoodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dischargePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        // TODO add your handling code here:
        infoPanel.setVisible(true);
        bookingPanel.setVisible(false);
        viewMapPanel.setVisible(false);
        customerPanel.setVisible(false);
        viewFoodPanel.setVisible(false);
        dischargePanel.setVisible(false);

    }//GEN-LAST:event_infoBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UserLogin().setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void bookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingBtnActionPerformed
        // TODO add your handling code here:
        infoPanel.setVisible(false);
        bookingPanel.setVisible(true);
        viewMapPanel.setVisible(false);
        customerPanel.setVisible(false);
        viewFoodPanel.setVisible(false);
        dischargePanel.setVisible(false);

    }//GEN-LAST:event_bookingBtnActionPerformed

    private void viewFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFoodBtnActionPerformed
        // TODO add your handling code here:
        infoPanel.setVisible(false);
        bookingPanel.setVisible(false);
        viewMapPanel.setVisible(false);
        customerPanel.setVisible(false);
        viewFoodPanel.setVisible(true);
        dischargePanel.setVisible(false);

    }//GEN-LAST:event_viewFoodBtnActionPerformed

    private void settingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingBtnActionPerformed
        // TODO add your handling code here:
        fnameTxt.setEnabled(true);
        lnameTxt.setEnabled(true);
        phoneTxt.setEnabled(true);
        cmndTxt.setEnabled(true);

        savebtn.setEnabled(true);
        cancelBtn.setEnabled(true);
    }//GEN-LAST:event_settingBtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        String fname = fnameTxt.getText();
        String lname = lnameTxt.getText();
        String phone = phoneTxt.getText();
        String cmnd = cmndTxt.getText();

        boolean hopLe = true;
        CheckText ct = new CheckText();

        if (fname.equals("")) {
            fnameWrong.setText("First name empty");
            hopLe = false;
        }
        if (fname.equals("")) {
            fnameWrong.setText("Last name empty");
            hopLe = false;
        }
        if (!ct.isPhoneNumber(phone)) {
            phoneWrong.setText("Phone must has maxinum 11 numbers");
            hopLe = false;
        }
        if (!ct.isCmnd(cmnd)) {
            cmndWrong.setText("ID must has 12 numbers");
            hopLe = false;
        }

        if (hopLe) {
            staff.setHo(fname);
            staff.setTen(lname);
            staff.setSdt(phone);
            staff.setCmnd(cmnd);
            if (staffDao.updateStaffInfo(staff)) {
                JOptionPane.showMessageDialog(rootPane, "Update info successful");
                resetInfolabels();
                showInfo();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Update info failed");
            }
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        fnameTxt.setText(staff.getHo());
        lnameTxt.setText(staff.getTen());
        phoneTxt.setText(staff.getSdt());
        cmndTxt.setText(staff.getCmnd());

        fnameTxt.setEnabled(false);
        lnameTxt.setEnabled(false);
        phoneTxt.setEnabled(false);
        cmndTxt.setEnabled(false);
        quitNoRadio.setEnabled(false);
        quitYesRadio.setEnabled(false);

        savebtn.setEnabled(false);
        cancelBtn.setEnabled(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void quitYesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitYesRadioActionPerformed
        // TODO add your handling code here:
        quitNoRadio.setSelected(false);
    }//GEN-LAST:event_quitYesRadioActionPerformed

    private void quitNoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitNoRadioActionPerformed
        // TODO add your handling code here:
        quitYesRadio.setSelected(false);
    }//GEN-LAST:event_quitNoRadioActionPerformed

    private void viewMapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMapBtnActionPerformed
        // TODO add your handling code here:
        infoPanel.setVisible(false);
        bookingPanel.setVisible(false);
        viewMapPanel.setVisible(true);
        customerPanel.setVisible(false);
        viewFoodPanel.setVisible(false);
        dischargePanel.setVisible(false);
    }//GEN-LAST:event_viewMapBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        infoPanel.setVisible(false);
        bookingPanel.setVisible(false);
        viewMapPanel.setVisible(false);
        customerPanel.setVisible(true);
        viewFoodPanel.setVisible(false);
        dischargePanel.setVisible(false);
    }//GEN-LAST:event_customerBtnActionPerformed

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        // TODO add your handling code here:
        infoPanel.setVisible(false);
        bookingPanel.setVisible(false);
        viewMapPanel.setVisible(false);
        customerPanel.setVisible(false);
        viewFoodPanel.setVisible(false);
        dischargePanel.setVisible(true);
    }//GEN-LAST:event_payBtnActionPerformed

    private void sortCusCbBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sortCusCbBoxItemStateChanged
        // TODO add your handling code here:

        String sortChoose = sortCusCbBox.getSelectedItem().toString();
        ArrayList<KhachHang> tempKhList = khList;
        switch (sortChoose) {
            case "All": {
                khTableModel.setRowCount(0);
                showCusList(khList);
                break;
            }
            case "Last name": {
                khTableModel.setRowCount(0);
                tempKhList.sort((KhachHang a, KhachHang b) -> {
                    return a.getTen().compareTo(b.getTen());
                });
                showCusList(tempKhList);
                break;
            }
            case "Number of rent": {
                khTableModel.setRowCount(0);
                tempKhList.sort((KhachHang a, KhachHang b) -> {
                    return b.getSolan_thuesan() - a.getSolan_thuesan();
                });
                showCusList(tempKhList);
                break;
            }
        }
    }//GEN-LAST:event_sortCusCbBoxItemStateChanged

    private void cancelCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCusBtnActionPerformed
        // TODO add your handling code here:
        cusIdTxt.setEnabled(true);
        cusUsernameTxt.setEnabled(true);

        resetCusTexts();
        resetCusLabels();
    }//GEN-LAST:event_cancelCusBtnActionPerformed

    private void updateCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCusBtnActionPerformed
        // TODO add your handling code here:
        resetCusLabels();

        String id = cusIdTxt.getText();
        String fname = cusFnameTxt.getText();
        String lname = cusLnameTxt.getText();
        String phone = cusPhoneTxt.getText();
        String cmnd = cusCmndTxt.getText();
        String username = cusUsernameTxt.getText();

        int index = khTable.getSelectedRow();

        boolean hopLe = true;
        CheckText ct = new CheckText();

        if (fname.equals("")) {
            cusFnameWrong.setText("First name is empty!");
            hopLe = false;
        }

        if (lname.equals("")) {
            cusLnameWrong.setText("Last name is empty!");
            hopLe = false;
        }

        if (phone.equals("")) {
            cusPhoneWrong.setText("Phone is empty!");
            hopLe = false;

        } else if (!ct.isPhoneNumber(phone)) {
            cusPhoneWrong.setText("Phone is invalid, must me number");
            hopLe = false;
        }

        if (cmnd.equals("")) {
            cusCmndWrong.setText("ID is empty!");
            hopLe = false;
        } else if (!ct.isCmnd(cmnd)) {
            cusCmndWrong.setText("ID is invalid, maximum 12 numbers");
            hopLe = false;
        }

        if (hopLe) {

            KhachHang kh = new KhachHang(id, fname, lname, phone, cmnd, 0, username, "normal");

            if (khDao.updateCusInfo(kh)) {

                khList.set(index, kh);

                khTableModel.setRowCount(0);
                resetCusTexts();
                resetCusLabels();
                cusIdTxt.setEnabled(true);
                cusUsernameTxt.setEnabled(true);
                showCusList(khList);

                JOptionPane.showMessageDialog(rootPane, "Update customer info successfully!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Update customer info failed!");
            }
        }
    }//GEN-LAST:event_updateCusBtnActionPerformed

    private void addCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCusBtnActionPerformed
        // TODO add your handling code here:

        resetCusLabels();

        String id = cusIdTxt.getText();
        String fname = cusFnameTxt.getText();
        String lname = cusLnameTxt.getText();
        String phone = cusPhoneTxt.getText();
        String cmnd = cusCmndTxt.getText();
        String username = cusUsernameTxt.getText();

        boolean hopLe = true;
        CheckText ct = new CheckText();

        if (id.equals("")) {
            cusIdWrong.setText("ID is empty!");
            hopLe = false;
        } else if (khDao.checkCusId(id)) {
            cusIdWrong.setText("ID is existed!");
            hopLe = false;
        }

        if (fname.equals("")) {
            cusFnameWrong.setText("First name is empty!");
            hopLe = false;
        }

        if (lname.equals("")) {
            cusLnameWrong.setText("Last name is empty!");
            hopLe = false;
        }

        if (phone.equals("")) {
            cusPhoneWrong.setText("Phone is empty!");
            hopLe = false;

        } else if (!ct.isPhoneNumber(phone)) {
            cusPhoneWrong.setText("Phone is invalid, must me number");
            hopLe = false;
        }

        if (cmnd.equals("")) {
            cusCmndWrong.setText("ID is empty!");
            hopLe = false;
        } else if (!ct.isCmnd(cmnd)) {
            cusCmndWrong.setText("ID is invalid, maximum 12 numbers");
            hopLe = false;
        }

        if (username.equals("")) {
            cusUsernameWrong.setText("Username is empty!");
            hopLe = false;
        } else if (accDao.checkUsername(username)) {
            cusUsernameWrong.setText("Username is already existed!");
            hopLe = false;
        }

        if (hopLe) {

            KhachHang kh = new KhachHang(id, fname, lname, phone, cmnd, 0, username, "normal");

            if (accDao.addAccount(username, "khach") && khDao.addCus(kh)) {
                khList.add(kh);
                khTableModel.addRow(new Object[]{id, fname, lname, phone, cmnd, 0, username, "normal"});
                JOptionPane.showMessageDialog(rootPane, "Add customer successfully!"
                    + "\nusername: " + username + "\npassword: 123"
                    + "\nChange password before use");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Add customer failed!");
            }
        }
    }//GEN-LAST:event_addCusBtnActionPerformed

    private void khTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khTableMouseClicked
        // TODO add your handling code here:
        cusIdTxt.setEnabled(false);
        cusUsernameTxt.setEnabled(false);

        int index = khTable.getSelectedRow();

        if (index == -1) {

        } else {
            KhachHang kh = khList.get(index);

            cusIdTxt.setText(kh.getMakh());
            cusFnameTxt.setText(kh.getHo());
            cusLnameTxt.setText(kh.getTen());
            cusPhoneTxt.setText(kh.getSdt());
            cusCmndTxt.setText(kh.getCmnd());
            cusUsernameTxt.setText(kh.getTaikhoan());

        }
    }//GEN-LAST:event_khTableMouseClicked

    private void foodTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodTableMouseClicked
        // TODO add your handling code here:

        int index = foodTable.getSelectedRow();
        if (index == -1) {
        } else {
            DichVu dv = dvList.get(index);
            ImageIcon image = new ImageIcon(dv.getHinhanh());
            Image temp = image.getImage();
            ImageIcon scaledImage = new ImageIcon(temp.getScaledInstance(foodImageLabel.getWidth(), foodImageLabel.getHeight(), Image.SCALE_SMOOTH));
            foodImageLabel.setIcon(scaledImage);
        }
    }//GEN-LAST:event_foodTableMouseClicked

    public void showInfo() {
        idTxt.setText(staff.getManv());
        fnameTxt.setText(staff.getHo());
        lnameTxt.setText(staff.getTen());
        phoneTxt.setText(staff.getSdt());
        cmndTxt.setText(staff.getCmnd());
        if (staff.isTrangthainghi()) {
            quitYesRadio.setSelected(true);
        } else {
            quitNoRadio.setSelected(true);
        }

        fnameTxt.setEnabled(false);
        lnameTxt.setEnabled(false);
        phoneTxt.setEnabled(false);
        cmndTxt.setEnabled(false);
        quitNoRadio.setEnabled(false);
        quitYesRadio.setEnabled(false);

        savebtn.setEnabled(false);
        cancelBtn.setEnabled(false);
    }

    public void resetInfolabels() {
        fnameWrong.setText(" ");
        lnameWrong.setText(" ");
        phoneWrong.setText(" ");
        cmndWrong.setText(" ");
    }
    
    public void resetCusTexts() {
        cusIdTxt.setText("");
        cusFnameTxt.setText("");
        cusLnameTxt.setText("");
        cusPhoneTxt.setText("");
        cusCmndTxt.setText("");
        cusUsernameTxt.setText("");
    }

    public void resetCusLabels() {
        cusIdWrong.setText(" ");
        cusFnameWrong.setText(" ");
        cusLnameWrong.setText(" ");
        cusPhoneWrong.setText(" ");
        cusCmndWrong.setText(" ");
        cusUsernameWrong.setText(" ");
    }
    
    public void showCusList(ArrayList<KhachHang> khList) {
        for (KhachHang kh : khList) {
            khTableModel.addRow(new Object[]{kh.getMakh(), kh.getHo(), kh.getTen(),
                kh.getSdt(), kh.getCmnd(), kh.getSolan_thuesan(), kh.getTaikhoan(), kh.getLoaiTk()});
        }
    }
    
    public void showFoodList(ArrayList<DichVu> dvList) {
        for (DichVu dv : dvList) {
            dvTableModel.addRow(new Object[]{dv.getMadv(), dv.getTendv(),
                dv.getDvt(), dv.getDongia(), dv.getHinhanh()});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffGUI("phi", "nhanvien").setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCusBtn;
    private javax.swing.JButton bookingBtn;
    private javax.swing.JPanel bookingPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelCusBtn;
    private javax.swing.JButton changepwdBtn;
    private javax.swing.JTextField cmndTxt;
    private javax.swing.JLabel cmndWrong;
    private javax.swing.JTextField cusCmndTxt;
    private javax.swing.JLabel cusCmndWrong;
    private javax.swing.JTextField cusFnameTxt;
    private javax.swing.JLabel cusFnameWrong;
    private javax.swing.JTextField cusIdTxt;
    private javax.swing.JLabel cusIdWrong;
    private javax.swing.JTextField cusLnameTxt;
    private javax.swing.JLabel cusLnameWrong;
    private javax.swing.JTextField cusPhoneTxt;
    private javax.swing.JLabel cusPhoneWrong;
    private javax.swing.JTextField cusUsernameTxt;
    private javax.swing.JLabel cusUsernameWrong;
    private javax.swing.JButton customerBtn;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel dischargePanel;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel fnameWrong;
    private javax.swing.JLabel foodImageLabel;
    private javax.swing.JTable foodTable;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton infoBtn;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable khTable;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JLabel lnameWrong;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton payBtn;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JLabel phoneWrong;
    private javax.swing.JRadioButton quitNoRadio;
    private javax.swing.JRadioButton quitYesRadio;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton settingBtn;
    private javax.swing.JComboBox<String> sortCusCbBox;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JButton updateCusBtn;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton viewFoodBtn;
    private javax.swing.JPanel viewFoodPanel;
    private javax.swing.JButton viewMapBtn;
    private javax.swing.JPanel viewMapPanel;
    // End of variables declaration//GEN-END:variables
}
